In [2]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten, Dense
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical
import matplotlib.pyplot as plt

Aqui preprocesaremos las etiquetas de entrada

In [3]:
# Supongamos que tienes una serie de tiempo representada como un numpy array 'X' y las etiquetas 'y' o 'z'
X=np.array(np.linspace(0.7,1.2,100)) #Para nosotros, la 'serie de tiempo' seran los datos de flujo, X de un solo espectro

y=np.linspace(0,5,5)
z=np.array(["a","b","c","d","b"])

# Preprocesar las etiquetas utilizando LabelEncoder
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)  # Convierte etiquetas de texto a números enteros
y_onehot = to_categorical(y_encoded)  # Convierte etiquetas numéricas a one-hot encoding ej: rojo=[1,0,0], azul=[0,1,0], verde=[0,0,1]

z_encoded = label_encoder.fit_transform(z)  # Convierte etiquetas de texto a números enteros
z_onehot = to_categorical(z_encoded)  # Convierte etiquetas numéricas a one-hot encoding ej: rojo=[1,0,0], azul=[0,1,0], verde=[0,0,1]

In [4]:
print(y)
print(z)

[0.   1.25 2.5  3.75 5.  ]
['a' 'b' 'c' 'd' 'b']


In [5]:
print(y_encoded)
print(z_encoded)

[0 1 2 3 4]
[0 1 2 3 1]


In [6]:
print(y_onehot)
print(z_onehot)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]]


Dividiremos el conjunto de datos en datos de entrenamiento y datos de prueba

In [7]:
# Dividir el conjunto de datos en entrenamiento y prueba
y=np.random.randint(0,6,100) #Son las etiquetas asignadas a cada punto de la lista de flujo
y_encoded = label_encoder.fit_transform(y)
y_onehot = to_categorical(y_encoded)

X_train, X_test, y_train, y_test = train_test_split(X, y_onehot, test_size=0.2, random_state=42)


In [8]:
print(len(X))
print(X)

100
[0.7        0.70505051 0.71010101 0.71515152 0.72020202 0.72525253
 0.73030303 0.73535354 0.74040404 0.74545455 0.75050505 0.75555556
 0.76060606 0.76565657 0.77070707 0.77575758 0.78080808 0.78585859
 0.79090909 0.7959596  0.8010101  0.80606061 0.81111111 0.81616162
 0.82121212 0.82626263 0.83131313 0.83636364 0.84141414 0.84646465
 0.85151515 0.85656566 0.86161616 0.86666667 0.87171717 0.87676768
 0.88181818 0.88686869 0.89191919 0.8969697  0.9020202  0.90707071
 0.91212121 0.91717172 0.92222222 0.92727273 0.93232323 0.93737374
 0.94242424 0.94747475 0.95252525 0.95757576 0.96262626 0.96767677
 0.97272727 0.97777778 0.98282828 0.98787879 0.99292929 0.9979798
 1.0030303  1.00808081 1.01313131 1.01818182 1.02323232 1.02828283
 1.03333333 1.03838384 1.04343434 1.04848485 1.05353535 1.05858586
 1.06363636 1.06868687 1.07373737 1.07878788 1.08383838 1.08888889
 1.09393939 1.0989899  1.1040404  1.10909091 1.11414141 1.11919192
 1.12424242 1.12929293 1.13434343 1.13939394 1.14444444 1.1

In [9]:
print(len(X_train))
print(X_train)

80
[0.97777778 1.14444444 0.83131313 0.91212121 1.04848485 0.77575758
 0.9020202  1.18484848 0.74545455 1.06363636 0.75555556 0.93737374
 1.12929293 0.84141414 1.16969697 0.72525253 1.03333333 1.02828283
 0.87676768 0.78080808 0.94747475 0.87171717 0.73535354 1.17979798
 0.83636364 0.7959596  1.10909091 0.82626263 1.01313131 0.76565657
 0.82121212 0.71515152 0.78585859 0.89191919 0.74040404 1.09393939
 0.73030303 1.02323232 0.88181818 1.14949495 0.98282828 1.2
 0.97272727 0.91717172 0.95252525 1.03838384 0.93232323 1.04343434
 1.00808081 1.18989899 1.0989899  0.90707071 0.99292929 0.94242424
 1.19494949 0.98787879 1.07878788 0.86161616 1.17474747 0.9979798
 1.01818182 1.12424242 0.88686869 0.84646465 0.70505051 0.96262626
 0.80606061 0.71010101 0.81616162 1.13939394 1.15959596 1.07373737
 1.13434343 1.11414141 0.8010101  1.0030303  1.05858586 0.77070707
 1.16464646 0.95757576]


In [10]:
print(len(X_test))
print(X_test)

20
[1.11919192 0.96767677 1.05353535 0.92727273 0.92222222 0.8969697
 0.81111111 1.1040404  0.75050505 0.7        0.79090909 0.85151515
 1.06868687 0.86666667 1.15454545 0.72020202 1.08383838 1.08888889
 0.76060606 0.85656566]


Definir el modelo de la red convolusional

In [11]:
#lLamamos el modelo CNN1D asi:
model = Sequential()

Agregamos una capa convolusional 1D

In [15]:
model.add(Conv1D(filters=32, kernel_size=3, activation='relu', input_shape=((X_train.shape[:1][0],1))))

Agregamos una capa de max pooling

In [12]:
model.add(MaxPooling1D(pool_size=2))

Aplanamos la salida para conectarla a capas densas

In [13]:
model.add(Flatten())

Agregamos capas densas

In [14]:
model.add(Dense(128, activation='relu'))

#model.add(Dense(len(label_encoder.classes_), activation='softmax'))  # Capa de salida con activación softmax para clasificación
model.add(Dense(units=1, activation='linear'))  # Capa de salida lineal para regresiónn

Compilamos el modelo

In [15]:
#model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy']) #para problema de clasificación
model.compile(optimizer='adam', loss='mean_squared_error', metrics=['mse'])  # Puedes ajustar el optimizador y la función de pérdida según tu tarea. Para regresión

Entrenamos el modelo

In [16]:
#model.fit(X_train, y_train, epochs=10, batch_size=32, validation_split=0.2) #el validation_split debe coincidir con el test_size del preprocesamiento.
history= model.fit(X_train, y_train, epochs=10, batch_size=32, validation_data=(X_test, y_test))

Epoch 1/10


ValueError: in user code:

    File "c:\users\daniel\appdata\local\programs\python\python38\lib\site-packages\keras\src\engine\training.py", line 1338, in train_function  *
        return step_function(self, iterator)
    File "c:\users\daniel\appdata\local\programs\python\python38\lib\site-packages\keras\src\engine\training.py", line 1322, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "c:\users\daniel\appdata\local\programs\python\python38\lib\site-packages\keras\src\engine\training.py", line 1303, in run_step  **
        outputs = model.train_step(data)
    File "c:\users\daniel\appdata\local\programs\python\python38\lib\site-packages\keras\src\engine\training.py", line 1080, in train_step
        y_pred = self(x, training=True)
    File "c:\users\daniel\appdata\local\programs\python\python38\lib\site-packages\keras\src\utils\traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "c:\users\daniel\appdata\local\programs\python\python38\lib\site-packages\keras\src\engine\input_spec.py", line 253, in assert_input_compatibility
        raise ValueError(

    ValueError: Exception encountered when calling layer 'sequential' (type Sequential).
    
    Input 0 of layer "conv1d" is incompatible with the layer: expected min_ndim=3, found ndim=1. Full shape received: (None,)
    
    Call arguments received by layer 'sequential' (type Sequential):
      • inputs=tf.Tensor(shape=(None,), dtype=float32)
      • training=True
      • mask=None


Evaluamos el modelo en el conjunto de prueba

In [ ]:
score = model.evaluate(X_test, y_test, verbose=0)
loss, accuracy=score[0], score[1]

print(f'Accuracy: {accuracy * 100:.2f}%')
print("Loss:", score[0])

Visualización del Rendimiento

In [17]:
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.legend()
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.show()

NameError: name 'history' is not defined

Predicciones

In [18]:
predictions = model.predict(X_test)

NameError: name 'X_new_data' is not defined